version: '3'
services:
  centos1:
    image: centos7-rssh
    container_name: node1
    hostname: node1
    ports:
      - "2200:22"

  centos2:
    image: centos7-rssh
    container_name: node2
    hostname: node2
    ports:
      - "2300:22"
